### ISSUE TITLE
Needs more synergy

### ISSUE THREAD

**Issue by samdunne** [Aidanie/datastructures.js#1]
Not enough synergy

**Comment by Aidanie** [comment]
I plan on leaping forward this week with my plan of attack while penetrating the rim of fire.

I'll be synergizing in an agile environment to provide turn-key solutions to this issue.

**Comment by samdunne** [comment]
Make sure to harness the cloud

**Comment by Aidanie** [comment]
I'll deploy both a public and private cloud. These will synergize in a platform agnostic way which will leverage the hybrid functionality of both.

**Comment by samdunne** [comment]
Ok I actually can no longer stomach this issue. Lets mark as resolved :P
